### ISSUE TITLE
Authentication Mode 4

### ISSUE THREAD

**Issue by danxfisher** [ffilardi/AxaptaAPI#11]
Is there any documentation for Authentication Mode 4: Impersonate as listed in the Web.config file?  I'm trying to get this work with the Azure AD Application Proxy and I feel like this would be the best way but I'm unable to get it to work with an on-prem web server.

**Comment by ffilardi** [comment]
Hey Dan, the doc is not updated with the auth mode 4. but it's the same as auth mode 3. Not sure if this is the best option for your case, I'd need more details to help you.

**Comment by munib00** [comment]
Hi Dan,
Follow this blog to set up the trusted intermediary. 
https://daxmusings.codecrib.com/2011/11/trusted-intermediary-in-aif-services.html
Let us know how you go.
