### ISSUE TITLE
Error "Invalid expression term 'int'" in "ServiceConfig.cs	39

### ISSUE THREAD

**Issue by munib00** [ffilardi/AxaptaAPI#8]
When using Visual studio 2015 it will error during compile for this line.
           ` if (Int32.TryParse(ConfigurationManager.AppSettings["API_AUTH_MODE"], out int mode))`

You can break it into two lines
```
            int mode = 0;
            if (Int32.TryParse(ConfigurationManager.AppSettings["API_AUTH_MODE"], out mode))
```
You can close this issue. Just wanted to write it, incase someone else ran into it.

**Comment by fraga** [comment]
@munib00 looks like you included this change in your PR thanks for that

**Comment by ffilardi** [comment]
Fixed
