### ISSUE TITLE
Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by frandisag** [ffilardi/AxaptaAPI#9]
please help me ... :(

**Comment by fraga** [comment]
Hi @frandisag 

Sorry to hear you're having issues with this. We can't do much before you provide us more information like repro steps, call stack, ax 2012 version, basically how could we repro your issue?

**Comment by frandisag** [comment]
i use ax 2012 r2, actualy this's my fault. i ran app outside the domain server.
now i can running this api on my computer, thanks a lot for code 👍 , you re really awesome,
have a great day

**Comment by fraga** [comment]
Glad you solved it @frandisag.

Rel to the code, it was all @ffilardi and AX community ;)

@ffilardi you may close the issue
